# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'GT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GT
   pod 'ObjectMapper'
   pod 'Alamofire', '~> 5.0'
   pod 'PushNotifications', '2.0.0'
   pod 'Groot'
end
