# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'GT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GT
   pod 'JZCalendarWeekView'
   pod 'ObjectMapper'
   pod 'Alamofire', '~> 5.0'
   pod 'pod PushNotifications'
end
